     - name: copy docker-compose
       copy:
         src: /docker-compose.yaml #location of docker compose file in loacl
         dest: /home/ec2-user/docker-compose.yaml

     - name: docker login
       vars:
         ansible_python_interpreter: /usr/bin/python
       docker_login:
          registry_url: "{{ docker_registry }}"
          username: "{{ docker_username }}"
          password: "{{ docker_password }}"
     - name: deploy Docker Compose stack
      # command: docker-compose -f /home/ec2-user/docker-compose.yaml up
       vars:
         ansible_python_interpreter: /usr/bin/python
       community.docker.docker_compose:
          project_src: /home/ec2-user   